import { ElementRef, OnInit, EventEmitter, Renderer2 } from '@angular/core';
import { DfpIDGeneratorService } from '../service';
export declare class DfpVideoDirective implements OnInit {
    private platformId;
    private elementRef;
    private renderer;
    private dfpIDGenerator;
    width: number;
    height: number;
    adTag: string;
    adActions: EventEmitter<'play' | 'pause' | 'resume'>;
    adEvents: EventEmitter<any>;
    contentPlayer: HTMLVideoElement;
    adContainer: HTMLElement;
    private contentCompleteCalled;
    private adDisplayContainer;
    private adsLoader;
    private adsManager;
    private adsDone;
    constructor(platformId: Object, elementRef: ElementRef, renderer: Renderer2, dfpIDGenerator: DfpIDGeneratorService);
    ngOnInit(): void;
    play(): void;
    pause(): void;
    resume(): void;
    setUpIMA(): void;
    initialUserAction(): void;
    requestAds(adTagUrl: any): void;
    contentEnded(): void;
    onAdsManagerLoaded(adsManagerLoadedEvent: any): void;
    startAdsManager(adsManager: any): void;
    onContentPauseRequested(): void;
    onContentResumeRequested(): void;
    onAdEvent(adEvent: any): void;
    onAdError(adErrorEvent: any): void;
    resumeAfterAd(): void;
    pauseForAd(): void;
    loadAds(): void;
}
